name = "GraphMakie"
uuid = "1ecd5474-83a3-4783-bb4f-06765db800d2"
authors = ["Simon Danisch", "Hans WÃ¼rfel"]
version = "0.2.0"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"

[compat]
LightGraphs = "1.3"
Makie = "0.14"
NetworkLayout = "0.4"
julia = "1"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CairoMakie"]
